<!-- Message de notification -->

<!-- Code HTML à écrire -->


<!-- Liste des aliments -->
<aside id="notice" class="hidden notice" >
    <p>Votre réservation est bien enregistrée, nous vous en remercions.</p>
</aside>

<table class="generic-table meal-list">
    <caption>Carte du restaurant</caption>
    <tbody>
        <!-- Code HTML à écrire -->
        
        <?php foreach ($meals as $meal){ ?>
            <tr>
                <td><img src="<?=$wwwUrl?>/images/meals/<?=$meal['Photo']?>" alt=""/></td>
                <td><strong><?=$meal['Name']?></strong><br><?=$meal['Description']?></td>
                <td class="number"><strong><?= number_format($meal['SalePrice'], 2) ?></strong> €</td>
            </tr>
        <?php } ?>
        
    </tbody>
</table>

<?php if (isset($_GET['Booked']) == true){ ?>
    <script src="<?=$wwwUrl?>/js/classes/index/index.js"></script>
<?php } ?>